### ISSUE TITLE
Speedup from kc-cpp2.cpp to kc-c1.c

### ISSUE THREAD

**Issue by ksahlin** [lh3/kmer-cnt#4]
Hi @lh3,

Thanks for this survey! It's been very useful for someone learning C++. 

I have a newbie question about the 9-10x speedup you see when going from `kc-cpp2.cpp` to `kc-c1.c`. From the way I'm interpreting it, you write that the reason for the speedup is that "kc-c1.c packs k-mers no longer than 32bp into 64-bit integers". 

**Q1**. But is this really the cause of the drastic speedup, or is it rather something more foundational within your library `khashl.c`? The reason I ask is that I'm only seeing about 10-20% speedup when I do bit packing (with your function`kmer_to_uint64`) of k-mers and then using Martin Ankerl's robin_hood hash table library, compared to only using the robin hood library inserting the k-mers directly. 

**Q2** Furthermore, if `khashl.c` is responsible for the major speedup and not the bit packing itself, would you know (or guesstimate) if is it possible to use `khashl.c` at the same efficiency in C++? 

Some background as to why I did some analysis on this: I want to store all positions of a k-mer on a chromosome in a vector or similar. I did some profiling on using either a robin hood hash `map: std::string -> std::vector` (inserting the k-mer directly), or using a robin hood hash map  `u_int64 -> std::vector` (bit packing the k-mer first). The difference is only about 10-20% faster for `u_int64 -> std::vector`.  In my profiling, I made sure that no other operation (such as vector::pushback) was the bottleneck.  Furthermore, somewhat disappointing, my C++ program using 

``` 
uint64_t bkmer = kmer_to_uint64(kmer, kmask);   
h[bkmer].push_back(kmer_pos);  # uint64 -> std::vector, Martin Ankerl's robin_hood hash table library
```
is almost as slow as my python program using 

```
h[hash(k)].append(kmer_pos) # int -> list
```

Any feedback you can give on this is appreciated.

**Comment by lh3** [comment]
For k-mer counting, packing reduces the time complexity from O(kL) to O(L), where k is the k-mer length and L is the total length of input sequences. It also reduces space and cache misses. It is the major source of improvement.

I have evaluated `robin_hood.h` before and can confirm it is as good as `khashl.h`. I am surprised by the marginal performance gain. What's the k-mer length? Note that this repo is mostly for long k-mers (k>15). For short k-mers, we don't need to use a hash table library.

For indexing a genome, the preferred way is to have an array of (k-mer, chr, pos) tuples in memory, sort it by k-mer and index k-mers in a hash table. In this hash table, the key is the packed k-mer and the value is the (offset,count) tuple, where offset is the offset in the array and count is the number of positions having the same k-mer. These positions are clustered in the array because it is sorted by k-mer. You can read [the minimap2 code](https://github.com/lh3/minimap2/blob/f7dc5799c567f406936033ea9fa7f11f6843385f/index.c#L191-L243) about this. Note that minimap2 also uses an ensemble of k-mers like in kc-c2. This complicates the code.

The advantage of this approach is that it saves lots of heap allocations, cache misses and memory. It is the better strategy for indexing one genome. The downside is that it usually takes much more memory for counting k-mers in high-coverage reads. KMC uses a similar sorting based algorithm to count k-mers. It has to use disk to keep a low memory footprint.

**Comment by ksahlin** [comment]
Oh, I see! You are bit packing by running a sliding window over the sequence, you do not pack each k-mer individually, which would obviously result in a lot of redundant packing... At least that is my current guess based on looking at the function at https://github.com/lh3/kmer-cnt/blob/master/kc-c1.c#L31. That makes more sense. I guess I was learning so much other stuff so didn't pay attention to this crucial detail. I will implement such a method instead.   
  
Also, thanks for the nudge in the right direction regarding indexing a reference. Super helpful. Then I will focus my time on implementing such an array indexing solution that you describe rather than creating a vector for each k-mer.

**Comment by shenwei356** [comment]
> bit packing by running a sliding window over the sequence

It's similar to rolling/recursive hash ([nthash](https://github.com/bcgsc/ntHash))

**Comment by lh3** [comment]
Actually not quite the same. The kmer-cnt packing doesn't incur any hash collisions but it only works for relatively short k-mers. nthash hashes k-mers and may map two distinct k-mers to the same hash.
